import type { Metadata } from "next";
import { Allura, Montserrat } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { ReactQueryClientProvider } from "@/providers/react-query-client";
import { NuqsAdapter } from "nuqs/adapters/next/app";

const allura = Allura({
  weight: ["400"],
  variable: "--font-allura",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-monteserrat",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Svyrn",
  description: "Generated by create next app",
  icons: [
    {
      rel: "icon",
      url: "/icons/logo.png",
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${allura.variable} ${montserrat.className} antialiased`}>
        <ReactQueryClientProvider>
          <NuqsAdapter>
            <Toaster richColors position="top-right" />
            {children}
          </NuqsAdapter>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
